apiVersion: v1        # BÜYÜK V — küçük yazılırsa Kubernetes reddeder
kind: Secret
metadata:
  name: restoran-secret
  namespace: default
type: Opaque
data:
  # Değerler base64 encoded olmalı
  # Terminalde kendin üretmek için: echo -n "değer" | base64
  db-host: cG9zdGdyZXMtc2VydmljZQ==   # "postgres-service"
  db-name: cmVzdG9yYW5kYg==            # "restorandb"
  db-user: YWRtaW4=                     # "admin"
  db-password: UGFzc3dvcmQxMjMh        # "Password123!" — bunu değiştir
