apiVersion: v1 
kind: Secret
metadata:
  name: restoran-secret
  namespace: default
type: Opaque
data:
  db-host: cG9zdGdyZXMtc2VydmljZQ==   # postgres-service
  db-name: cmVzdG9yYW5kYg==            # restorandb
  db-user: YWRtaW4=                     # admin
  db-password: UGFzc3dvcmQxMjMh        # Password123!
